image: markhobson/maven-chrome:jdk-17

stages:
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"


test:
  stage: test
  script:
    - mvn $MAVEN_OPTS clean package
    - mvn test
